// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtv_gw7wRheBp06p7BpnfuSY9xTFokjPU',
    appId: '1:920971395537:web:1f5544230d5f37e359a0f0',
    messagingSenderId: '920971395537',
    projectId: 'klinik-app-9a83a',
    authDomain: 'klinik-app-9a83a.firebaseapp.com',
    storageBucket: 'klinik-app-9a83a.appspot.com',
    measurementId: 'G-ELWJSK1P7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxcxxNUA4mxBIS8iiWmofS3fKtlY9COCI',
    appId: '1:920971395537:android:027ee8b665146c0059a0f0',
    messagingSenderId: '920971395537',
    projectId: 'klinik-app-9a83a',
    storageBucket: 'klinik-app-9a83a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG8kUB2dn0IU0KZOBJnUf5JySecZKlig8',
    appId: '1:920971395537:ios:e2b339d8cb88f19a59a0f0',
    messagingSenderId: '920971395537',
    projectId: 'klinik-app-9a83a',
    storageBucket: 'klinik-app-9a83a.appspot.com',
    iosBundleId: 'com.example.klinikApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG8kUB2dn0IU0KZOBJnUf5JySecZKlig8',
    appId: '1:920971395537:ios:e2b339d8cb88f19a59a0f0',
    messagingSenderId: '920971395537',
    projectId: 'klinik-app-9a83a',
    storageBucket: 'klinik-app-9a83a.appspot.com',
    iosBundleId: 'com.example.klinikApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtv_gw7wRheBp06p7BpnfuSY9xTFokjPU',
    appId: '1:920971395537:web:98489c5b6a30531259a0f0',
    messagingSenderId: '920971395537',
    projectId: 'klinik-app-9a83a',
    authDomain: 'klinik-app-9a83a.firebaseapp.com',
    storageBucket: 'klinik-app-9a83a.appspot.com',
    measurementId: 'G-TV9CB8GTKD',
  );
}
